### PR TITLE
fixed bug in cloudformation template preventing extra_json from being…

### PR DESCRIPTION
**Pull request by clausman**
… provided to chef cookbooks

### CODE REVIEW

**Comment by clausman** [comment]
See: https://github.com/awslabs/cfncluster/pull/83
For comments on topic. 

Closed that pr as requested.

**Comment by dougalb** [comment]
Can you also update for the ComputeFleet - https://github.com/clausman/cfncluster/blob/master/cloudformation/cfncluster.cfn.json#L2616

**Comment by clausman** [comment]
Whoops, missed that one, nice eye.

**Comment by dougalb** [comment]
Looks good. Will be pulling into 1.1.0.

**Pull request merged**
